
name: Deploy Functions Stack

on: push
         
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
        
    - name: Deploy Symptom functions Stack
      run: |
         aws cloudformation deploy \
          --template-file SymptomLogs.yml \
          --stack-name SymptomLogsStack \

    - name: Deploy environment Stack
      run: |
         aws cloudformation deploy \
          --template-file environment.yml \
          --stack-name environment \
          
    - name: Deploy symptomLogConsumer Stack
      run: |
         aws cloudformation deploy \
          --template-file symptomLogConsumer.yml \
          --stack-name symptomLogConsumer \

    
