name: Deploy Lambda Functions
on:
  push:
    branches:
      - main  

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
        
    - name: Remove conflicting package
      run: sudo apt-get remove -y python3-zipstream || true

    - name: Install zip
      run: sudo apt-get update && sudo apt-get install -y zip python3-zipstream-ng

# ---------- EnvironmentDataFunction_Iac ----------
    - name: Package environment lambda
      run: |
          cd environment
          zip -r ../environment.zip .
          cd ..

    - name: Deploy environment-data lambda
      run: |
          aws lambda update-function-code \
            --function-name EnvironmentDataFunction_Iac \
            --zip-file fileb://environment.zip

    # ---------- SymptomLogsFunction_Iac ----------
    - name: Package symptom-logs lambda
      run: |
          cd symptom-logs
          zip -r ../symptom-logs.zip .
          cd ..

    - name: Deploy symptom-logs lambda
      run: |
          aws lambda update-function-code \
            --function-name SymptomLogsFunction_Iac \
            --zip-file fileb://symptom-logs.zip

#----------------
      # ---------- SymptomConsumerFunction_Iac ----------
    - name: Package symptom-consumer lambda
      run: |
          cd symptom-consumer
          zip -r ../symptom-consumer.zip .
          cd ..

    - name: Deploy symptom-consumer lambda
      run: |
          aws lambda update-function-code \
            --function-name SymptomConsumerFunction_Iac \
            --zip-file fileb://symptom-consumer.zip
